using mdHWChecker.converter;
using mdHWChecker.service;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace mdHWChecker.gui
{
    public partial class MainWindow : Form
    {
        public MainWindow()
        {
            InitializeComponent();
            InitializeInformations();
        }

        private void InitializeInformations()
        {
            PleaseWaitWindow pleaseWaitWindow = new PleaseWaitWindow();
            pleaseWaitWindow.Show();

            SystemService systemService = new SystemService();
            systemService.InsertInformationsToListView(ref systemView);
            ProcessorService processorService = new ProcessorService();
            processorService.InsertInformationsToListView(ref processorView);
            MotherboardService motherboardService = new MotherboardService();
            motherboardService.InsertInformationsToListView(ref motherboardView);
            MemoryService memoryService = new MemoryService();
            memoryService.InsertInformationsToListView(ref memoryView);
            VideoAdapterService videoAdapterService = new VideoAdapterService();
            videoAdapterService.InsertInformationsToListView(ref videoAdapterView);
            AudioService audioService = new AudioService();
            audioService.InsertInformationsToListView(ref audioView);
            DrivesService drivesService = new DrivesService();
            drivesService.InsertInformationsToListView(ref drivesView);
            TemperatureService temperatureService = new TemperatureService();
            temperatureService.InsertInformationsToListView(ref temperatureView);

            pleaseWaitWindow.Close();
        }

        private void saveReportToolStripMenuItem_Click(object sender, EventArgs e)
        {
            SaveFileDialog saveFileDialog = new SaveFileDialog();
            saveFileDialog.Filter = "Text File|*.txt";
            saveFileDialog.Title = "Save Report As";
            DateTime nowTime = DateTime.Now;
            saveFileDialog.FileName = "mdhwc-report-" 
                + nowTime.Day 
                + nowTime.Month 
                + nowTime.Year 
                + "-" 
                + nowTime.Hour 
                + nowTime.Minute 
                + ".txt";
            
            if(saveFileDialog.ShowDialog() == DialogResult.OK)
            {
                string text = GetReportText();
                File.WriteAllText(saveFileDialog.FileName, text);
                System.Diagnostics.Process.Start(@saveFileDialog.FileName);
            }
        }

        private void refreshToolStripMenuItem_Click(object sender, EventArgs e)
        {
            InitializeInformations();
        }

        private void exitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }

        private void aboutToolStripMenuItem_Click(object sender, EventArgs e)
        {
            MessageBox.Show("mdHWChecker is a simple application to checking your computer's configuration. \n" +
                "Copyright © 2017 DultzDev. \n" +
                "mdHWChecker v0.1 \n" +
                "Visit www.dultzdev.com for updates and more informations. \n"
                , "About", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private String GetReportText()
        {
            DateTime nowTime = DateTime.Now;
            ListViewToStringConverter lvtsc = new ListViewToStringConverter();
            return "<--------- mdHWChecker Report --------->" + Environment.NewLine + Environment.NewLine
                    + "This is hardware report generated by mdHWChecker at " + nowTime.ToString() + " ." + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(systemView, "system") + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(processorView, "processor") + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(motherboardView, "motherboard") + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(videoAdapterView, "video adapter") + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(audioView, "audio") + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(drivesView, "drives") + Environment.NewLine + Environment.NewLine
                    + lvtsc.Convert(temperatureView, "temperature");
        }
    }
}
